# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Activate', 'Activate')], default=('Activate', 'Activate'), max_length=256),
        ),
    ]
